# DTU Data Cleaner

In [3]:
import pandas as pd 
import numpy as np
import os 
from pathlib import Path

In [ ]:
#CONFIG
DATA_PATH = "/Users/madshaakonsson/Desktop/7-semester/hmm-modelling/data/raw/dtu"
SAVE_PATH = "/Users/madshaakonsson/Desktop/7-semester/hmm-modelling/data/dtu" 

TEST_SIZE = 0.2

In [ ]:
def get_room_files(data_path):
    """
    Get all the files in the data_path directory and its subdirectories.
    """ 
    files = [f for f in Path(DATA_PATH).rglob("*") if f.is_file()]
    room_files = [f for f in files if "Room" in f.name]
    feed_back_files = [f for f in room_files if "feedback" in str(f)]
    timeseries_files = [f for f in room_files if "timeseries" in str(f)]
    return timeseries_files, feed_back_files

In [33]:
time_series, feed_back = get_room_files(DATA_PATH) 
weather_df = pd.read_csv(os.path.join(DATA_PATH, "weather.csv"))
holiday_df = pd.read_csv(os.path.join(DATA_PATH, "Denmark_DK.csv"))

print(f"Found {len(time_series)} time series files and {len(feed_back)} feedback files.")
print(f"Weather data shape: {weather_df.shape}")
print(f"Holiday data shape: {holiday_df.shape}")

print("Sample weather data:")
display(weather_df.head())
print("Sample holiday data:")
display(holiday_df.head())

Found 32 time series files and 11 feedback files.
Weather data shape: (2400, 9)
Holiday data shape: (30, 5)
Sample weather data:

,DateFrom,DateTo,mean_temp,mean_relative_hum,mean_wind_speed,mean_wind_dir,mean_pressure,mean_cloud_cover,mean_radiation
0,2024-02-09 12:00:00+00:00,2024-02-09 13:00:00+00:00,0.1,84.5,5.5,102.0,996.6,94.0,54.2
1,2024-02-09 11:00:00+00:00,2024-02-09 12:00:00+00:00,0.2,79.1,5.3,102.0,997.2,100.0,64.8
2,2024-02-09 10:00:00+00:00,2024-02-09 11:00:00+00:00,0.1,77.9,4.9,99.0,998.0,97.0,56.5
3,2024-02-09 09:00:00+00:00,2024-02-09 10:00:00+00:00,-0.4,81.2,4.2,94.0,998.6,91.0,51.7
4,2024-02-09 08:00:00+00:00,2024-02-09 09:00:00+00:00,-0.6,82.6,4.1,86.0,999.0,91.0,34.6

Sample holiday data:

,Date,Name,Type,Country Name,Country Code
0,2023-01-01,New Year's Day,['National holiday'],Denmark,DK
1,2023-02-14,Valentine's Day,['Observance'],Denmark,DK
2,2023-02-19,Carnival,['Observance'],Denmark,DK
3,2023-03-20T22:24:20+01:00,March Equinox,['Season'],Denmark,DK
4,2023-03-26T02:00:00+01:00,Daylight Saving Time starts,['Clock change/Daylight Saving Time'],Denmark,DK

In [ ]:


for i in range(len(time_series)):
    series_path = time_series[i] 
    if series_has_no_feedback(series_path, feed_back): 
        continue 
    
    df_series, df_feedback = load_series(series_path, feed_back) 
    df_series = clean_series(df_series) 
    df_feedback = clean_feedback(df_feedback)

([PosixPath('/Users/madshaakonsson/Desktop/7-semester/hmm-modelling/data/raw/dtu/timeseries/Room 008.csv'),
  PosixPath('/Users/madshaakonsson/Desktop/7-semester/hmm-modelling/data/raw/dtu/timeseries/Room 009.csv'),
  PosixPath('/Users/madshaakonsson/Desktop/7-semester/hmm-modelling/data/raw/dtu/timeseries/Room 032.csv'),
  PosixPath('/Users/madshaakonsson/Desktop/7-semester/hmm-modelling/data/raw/dtu/timeseries/Room 019.csv'),
  PosixPath('/Users/madshaakonsson/Desktop/7-semester/hmm-modelling/data/raw/dtu/timeseries/Room 057.csv'),
  PosixPath('/Users/madshaakonsson/Desktop/7-semester/hmm-modelling/data/raw/dtu/timeseries/Room 056.csv'),
  PosixPath('/Users/madshaakonsson/Desktop/7-semester/hmm-modelling/data/raw/dtu/timeseries/Room 054.csv'),
  PosixPath('/Users/madshaakonsson/Desktop/7-semester/hmm-modelling/data/raw/dtu/timeseries/Room 051.csv'),
  PosixPath('/Users/madshaakonsson/Desktop/7-semester/hmm-modelling/data/raw/dtu/timeseries/Room 045.csv'),
  PosixPath('/Users/madshaakonsson/Desktop/7-semester/hmm-modelling/data/raw/dtu/timeseries/Room 050.csv'),
  PosixPath('/Users/madshaakonsson/Desktop/7-semester/hmm-modelling/data/raw/dtu/timeseries/Room 046.csv'),
  PosixPath('/Users/madshaakonsson/Desktop/7-semester/hmm-modelling/data/raw/dtu/timeseries/Room 052.csv'),
  PosixPath('/Users/madshaakonsson/Desktop/7-semester/hmm-modelling/data/raw/dtu/timeseries/Room 053.csv'),
  PosixPath('/Users/madshaakonsson/Desktop/7-semester/hmm-modelling/data/raw/dtu/timeseries/Room 047.csv'),
  PosixPath('/Users/madshaakonsson/Desktop/7-semester/hmm-modelling/data/raw/dtu/timeseries/Room 061.csv'),
  PosixPath('/Users/madshaakonsson/Desktop/7-semester/hmm-modelling/data/raw/dtu/timeseries/Room 049.csv'),
  PosixPath('/Users/madshaakonsson/Desktop/7-semester/hmm-modelling/data/raw/dtu/timeseries/Room 048.csv'),
  PosixPath('/Users/madshaakonsson/Desktop/7-semester/hmm-modelling/data/raw/dtu/timeseries/Room 060.csv'),
  PosixPath('/Users/madshaakonsson/Desktop/7-semester/hmm-modelling/data/raw/dtu/timeseries/Room 058.csv'),
  PosixPath('/Users/madshaakonsson/Desktop/7-semester/hmm-modelling/data/raw/dtu/timeseries/Room 001.csv'),
  PosixPath('/Users/madshaakonsson/Desktop/7-semester/hmm-modelling/data/raw/dtu/timeseries/Room 015.csv'),
  PosixPath('/Users/madshaakonsson/Desktop/7-semester/hmm-modelling/data/raw/dtu/timeseries/Room 014.csv'),
  PosixPath('/Users/madshaakonsson/Desktop/7-semester/hmm-modelling/data/raw/dtu/timeseries/Room 016.csv'),
  PosixPath('/Users/madshaakonsson/Desktop/7-semester/hmm-modelling/data/raw/dtu/timeseries/Room 003.csv'),
  PosixPath('/Users/madshaakonsson/Desktop/7-semester/hmm-modelling/data/raw/dtu/timeseries/Room 013.csv'),
  PosixPath('/Users/madshaakonsson/Desktop/7-semester/hmm-modelling/data/raw/dtu/timeseries/Room 007.csv'),
  PosixPath('/Users/madshaakonsson/Desktop/7-semester/hmm-modelling/data/raw/dtu/timeseries/Room 012.csv'),
  PosixPath('/Users/madshaakonsson/Desktop/7-semester/hmm-modelling/data/raw/dtu/timeseries/Room 004.csv'),
  PosixPath('/Users/madshaakonsson/Desktop/7-semester/hmm-modelling/data/raw/dtu/timeseries/Room 010.csv'),
  PosixPath('/Users/madshaakonsson/Desktop/7-semester/hmm-modelling/data/raw/dtu/timeseries/Room 011.csv'),
  PosixPath('/Users/madshaakonsson/Desktop/7-semester/hmm-modelling/data/raw/dtu/timeseries/Room 005.csv'),
  PosixPath('/Users/madshaakonsson/Desktop/7-semester/hmm-modelling/data/raw/dtu/timeseries/Room 039.csv')],
 [PosixPath('/Users/madshaakonsson/Desktop/7-semester/hmm-modelling/data/raw/dtu/feedback/Room 009.csv'),
  PosixPath('/Users/madshaakonsson/Desktop/7-semester/hmm-modelling/data/raw/dtu/feedback/Room 019.csv'),
  PosixPath('/Users/madshaakonsson/Desktop/7-semester/hmm-modelling/data/raw/dtu/feedback/Room 054.csv'),
  PosixPath('/Users/madshaakonsson/Desktop/7-semester/hmm-modelling/data/raw/dtu/feedback/Room 001.csv'),
  PosixPath('/Users/madshaakonsson/Desktop/7-semester/hmm-modelling/data/raw/dtu/feedback/Room 015.csv'),
  PosixPath('/Users/madshaakonsson/Desktop/7-semester/hmm-modelling/data/raw/dtu/feedback/Room 016.csv'),
  PosixPath('/Users/madshaakonsson/Desktop/7-semester/hmm-modelling/data/raw/dtu/feedback/Room 007.csv'),
  PosixPath('/Users/madshaakonsson/Desktop/7-semester/hmm-modelling/data/raw/dtu/feedback/Room 012.csv'),
  PosixPath('/Users/madshaakonsson/Desktop/7-semester/hmm-modelling/data/raw/dtu/feedback/Room 004.csv'),
  PosixPath('/Users/madshaakonsson/Desktop/7-semester/hmm-modelling/data/raw/dtu/feedback/Room 010.csv'),
  PosixPath('/Users/madshaakonsson/Desktop/7-semester/hmm-modelling/data/raw/dtu/feedback/Room 039.csv')])